[package]
name = "web-push"
description = "Web push notification client with support for http-ece encryption."
version = "0.2.2"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
license = "Apache-2.0"
homepage = "https://github.com/pimeys/rust-web-push"
repository = "https://github.com/pimeys/rust-web-push"
documentation = "https://pimeys.github.io/rust-web-push/index.html"
readme = "README.md"
keywords = ["web-push", "http-ece"]
categories = ["web-programming", "asynchronous"]

[badges]
travis-ci = { repository = "pimeys/rust-web-push" }

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-timer = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ring = "0.9"
untrusted = "0.5"
rust-crypto = "0.2"
native-tls = "0.1"
base64 = "0.7"

[dev-dependencies]
argparse = "0.2"
