[package]
name = "web-push"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
license = "Apache 2.0"
homepage = "https://github.com/pimeys/rust-web-push"

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-timer = "0.1"
hyper = { git = "https://github.com/hyperium/hyper"}
hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
rustc-serialize = "0.3"
ring = "0.9"
untrusted = "0.5"
rust-crypto = "0.2"

[dev-dependencies]
argparse = "0.2"
