[package]
name = "web-push"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
license = "Apache 2.0"
homepage = "https://github.com/pimeys/rust-web-push"
repository = "https://github.com/pimeys/rust-web-push"
documentation = "https://pimeys.github.io/rust-web-push/web_push/index.html"
readme = "README.md"
keywords = ["web-push", "http-ece"]
categories = ["web-programming", "asynchronous"]

[badges]
travis-ci = { repository = "pimeys/rust-web-push" }

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-timer = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
rustc-serialize = "0.3"
ring = "0.9"
untrusted = "0.5"
rust-crypto = "0.2"
native-tls = "0.1"

[dev-dependencies]
argparse = "0.2"
